name: Delete ALL GitHub Artifact

on:
  workflow_dispatch:

jobs:
  delete-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Delete artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            response.data.artifacts.forEach(artifact => {
              console.log(`Deleting artifact: ID: ${artifact.id}, Workflow: ${artifact.workflow_run.head_branch}, SHA: Workflow: ${artifact.workflow_run.head_sha}, Created: ${artifact.created_at}, Download: ${artifact.archive_download_url}`);
              
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              
              console.log(`Artifact deleted successfully.`);
            });
