name: List Artifacts

on:
  workflow_dispatch:

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: github/cli-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: List artifacts
        run: |
          # List all artifacts in the repository
          echo "Listing artifacts in the repository..."

          artifacts=$(gh run artifacts list --repo ${{ github.repository }} --json name,id -q '.[] | "\(.name):\(.id)"')

          if [ -z "$artifacts" ]; then
            echo "No artifacts found."
          else
            echo "Artifacts found:"
            echo "$artifacts"
          fi
