name: List Artifacts

on:
  workflow_dispatch: # Allows you to trigger this manually

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/cli@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: List artifacts
        run: |
          echo "Listing artifacts for this repository..."
          gh run artifacts list --repo ${{ github.repository }}
